name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [20, 21, 22]
        base_version: [8, 8-minimal, 8.9-minimal, 9, 9-minimal, 9.3-minimal]

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/asterisk-rockylinux:${{ matrix.version }}-${{ matrix.base_version }}
          build-args: |
            ASTERISK_VERSION=${{ matrix.version }}
            BASE_VERSION=${{ matrix.base_version }}
          platforms: linux/amd64,linux/arm64
