name: Publish Docker Image

on:
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        asterisk_version: [22, 21, 20]
        base_version: [9-minimal, 8-minimal]

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/asterisk-rockylinux:${{ matrix.asterisk_version }}-${{ matrix.base_version }}
          build-args: |
            ASTERISK_VERSION=${{ matrix.asterisk_version }}
            BASE_VERSION=${{ matrix.base_version }}

  build-and-push-latest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Build and push latest
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/asterisk-rockylinux:latest
          build-args: |
            ASTERISK_VERSION=latest
            BASE_VERSION=9-minimal
