name: Publish Docker Image

on:
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        asterisk_version: [master, 23, 22, 21]
        base_version: [9-minimal]
        enable_chan_sip: [false, true]

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Build image to generate commit hash
        uses: docker/build-push-action@v6
        with:
          push: false
          load: true
          tags: temp-image
          build-args: |
            ASTERISK_VERSION=${{ matrix.asterisk_version }}
            BASE_VERSION=${{ matrix.base_version }}
            ENABLE_CHAN_SIP=${{ matrix.enable_chan_sip == true && 'true' || 'false' }}

      - name: Extract Asterisk commit hash
        id: commit
        run: |
          if [ -f /tmp/asterisk-commit.txt ]; then
            COMMIT_HASH=$(cat /tmp/asterisk-commit.txt | tr -d '\n')
            echo "hash=${COMMIT_HASH}" >> $GITHUB_OUTPUT
            echo "Asterisk commit hash: ${COMMIT_HASH}"
          else
            echo "File /tmp/asterisk-commit.txt not found"
            exit 1
          fi

      - name: Build and push with commit tag
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/asterisk-rockylinux:${{ matrix.asterisk_version }}-${{ matrix.base_version }}${{ matrix.enable_chan_sip == true && '-chansip' || '' }}-${{ steps.commit.outputs.hash }}
            ${{ secrets.DOCKER_USERNAME }}/asterisk-rockylinux:${{ matrix.asterisk_version }}-${{ matrix.base_version }}${{ matrix.enable_chan_sip == true && '-chansip' || '' }}
          build-args: |
            ASTERISK_VERSION=${{ matrix.asterisk_version }}
            BASE_VERSION=${{ matrix.base_version }}
            ENABLE_CHAN_SIP=${{ matrix.enable_chan_sip == true && 'true' || 'false' }}
